version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=bourse
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
